package ua.nure.sidak.SummaryTask4.constants;

/**
 * Stores most usable and valuable tags as for JSP pages either for parameters and attributes
 * @author eXce1z0r
 *
 */
public enum GeneralAttributes 
{	
	EN_LANG("enLang"), RU_LANG("ruLang"),
	
	TOUR_SEARCH_PANEL_LINK("tourSearchPanelLink"), USER_MANAGEMENT_PANEL_LINK("userManagementPanelLink"), 
	ORDERS_MANAGEMENT_PANEL_LINK("ordersManagementPanelLink"), CUSTOMER_PROFILE_PANEL_LINK("customerProfileLink"),
	
	LOG_IN_LINK_LABEL("logInLinkLabel"), LOGOUT_LINK_LABEL("logoutLinkLabel"), REGISTER_LINK_LABEL("registerLinkLabel"),
	
	LOGIN_LABEL("loginLabel"), MAIL_LABEL("mailLabel"), PASSWORD_LABEL("passwordLabel"), REPASSWORD_LABEL("rePasswordLabel"),
	TITLE_LABEL("titleLabel"), PRICE_LABEL("priceLabel"), DISCOUNT_LABEL("discountLabel"),
	
	REGISTER_BUTTON("registerButtonText"), LOG_BUTTON("logButtonText"), APPLY_UPDATE_BUTTON("applyUpdateButtonText"), 
	CREATE_BUTTON("createButtonText"), SEARCH_BUTTON("searchButtonText"), DESTROY_BUTTON("destroyButtonText"), MAKE_AN_ORDER_BUTTON("makeAnOrderButtonText"),
	
	SEARCH_FORM_NAME_LABEL("searchFormNameLabel"), SEARCH_FORM_MIN_TOUR_PRICE("searchFormMinTourPrice"), SEARCH_FORM_MAX_TOUR_PRICE("searchFormMaxTourPrice"),
	SEARCH_FORM_MIN_HUMANS("searchFormMinHumans"), SEARCH_FORM_MAX_HUMANS("searchFormMaxHumans"), SEARCH_FORM_TOUR_TYPE("searchFormTourType"),
	SEARCH_FORM_TOUR_LODGING_TYPE("searchFormTourLodgingType"),
	
	RESULT_FORM_NAME_LABEL("resultFormNameLabel"),
	
	TABLE_ID("tableIdColumn"), TABLE_TOUR_INFO("tableTourInfoColumn"), TABLE_ORDER_STATUS("tableOrderStatusColumn"), 
	TABLE_USER_INFO("tableUserInfoColumn"),
	TABLE_LOGIN("tableLoginColumn"), TABLE_MAIL("tableMailColumn"), TABLE_PASSWORD("tablePasswordColumn"), 
	TABLE_ROLE("tableRoleColumn"), TABLE_ACCOUNT_STATUS("tableAccountStatusColumn"), TABLE_ACTION("tableActionColumn"),
	
	TABLE_TITLE_COLUMN("tableTitleColumn"), TABLE_INFO_COLUMN("tableInfoColumn"), TABLE_PRICE_COLUMN("tablePriceColumn"),
	TABLE_TYPE_COLUMN("tableTypeColumn"), TABLE_LODGING_TYPE_COLUMN("tableLodgingTypeColumn"), TABLE_TOURISTS_AMOUNT_COLUMN("tableTouristsAmountColumn"),
	TABLE_DISCOUNT_COLUMN("tableDiscountColumn"), TABLE_HOT_COLUMN("tableHotColumn"),
	
	DISCOUNT_STEP_CONFIG_LABEL("discountStepConfigLabel"), DISCOUNT_LIMIT_CONFIG_LABEL("discountLimitConfigLabel"),
	NON_USER_DISCOUNT_STUB("nonUserDiscountStub"),
	
	AUTO_GENERATED_STUB("autoGeneratedStub"),
	
	ERROR_MESSAGE_EL_TAG("errorMessage"), SUCCESS_MASSEGE_EL_TAG("successMessage"),
	
	USER_LOGIN_EL_TAG("loginField"), USER_MAIL_EL_TAG("mailField"), USER_PASSWORD_EL_TAG("passwordField"),
	
	ORDERS_LIST("ordersList"), ORDER_STATUSES_LIST("orderStatusesList"), DISCOUNT_AVAILABLE_FUNCTIONALITY("discountFunctionality"),
	
	ADMIN_CONTROLL_PANE("adminPaneAccess"), MANAGER_CONTROLL_PANE("managerPaneAccess"), ORDER_TOUR_PANE("orderTourPaneAccess"),
	
	SESSION_USER_ID("userId"), SESSION_USER_ROLE("userRole"), SESSION_USER_LOGIN("userName"), SESSION_USER_MAIL("userMail"), SESSION_CLIENT_LOCALE("clientLocale"),;
	;
	
	private String value;
	
	GeneralAttributes(String string)
	{
		this.value = string;
	}
	
	public String getValue()
	{
		return this.value;
	}
}
