<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" isELIgnored="false" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/WEB-INF/tld/webSiteLib.tld" prefix="website" %>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Users management page</title>
		
		<link rel="stylesheet" type="text/css" href="style/bootstrap.min.css">
	</head>
	<body style="min-width: 1000px; min-height: 700px;">
	
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="top: 0; width: 100%; min-width: 1000px;">
		  <div class="container">
		    <a class="navbar-brand" href="controller?command=tourListCommand"><website:printWebsiteTitle /></a>
		
		    <div class="collapse navbar-collapse show" id="navbarsExample07">
		      <ul class="navbar-nav mr-auto">
		      
		        <li class="nav-item" style="min-width: 110px;">
		          <a class="nav-link" href="controller?command=tourListCommand">${tourSearchPanelLink}</a>
		        </li>
		        
		        <li class="nav-item" style="min-width: 100px;">	
					<a class="nav-link" href="controller?command=toUserManagementPageCommand">${userManagementPanelLink}</a>
				</li>
		        
		        <li class="nav-item" style="min-width: 100px; margin-right: 200px;">
						<a class="nav-link" href="controller?command=toOrdersManagementPageCommand">${ordersManagementPanelLink}</a>	
				</li>
		        
		        <li style="margin-right: 10px;">
					<a href="controller?command=logoutCommand">${logoutLinkLabel}</a>
				</li>
		        
		        <li style="float:right;">
			        <div id="language_controls">
						<a href="controller?command=toUserManagementPageCommand&language=en">${enLang}</a>
						<a href="controller?command=toUserManagementPageCommand&language=ru">${ruLang}</a>
					</div>
		        </li>
		        
		      </ul>
		    </div>
		  </div>
		</nav>	
		
		<div id="profile_ifo">
			<p>${loginLabel}: ${userName}</p>
			<p>${mailLabel}: ${userMail}</p>
		</div>
		
		<div id="users" style="width:100%; overflow-x: scroll;">
			<table style="text-align: center; vertical-align: middle; border: 1px solid black;">
			
				<tr>
					<td style="border: 1px solid black;">${tableIdColumn}</td>
					<td style="border: 1px solid black;">${tableLoginColumn}</td>
					<td style="border: 1px solid black;">${tableMailColumn}</td>
					<td style="border: 1px solid black;">${tablePasswordColumn}</td>
					<td style="border: 1px solid black;">${tableRoleColumn}</td>
					<td style="border: 1px solid black;">${tableAccountStatusColumn}</td>
					<td style="border: 1px solid black;">${tableActionColumn}</td>
				</tr>
				
				<tr>
					<form action="controller" method="post">
						
						<input type="hidden" name="command" value="createNewUserActionCommand"/>
							
						<td style="border: 1px solid black;">
							${autoGeneratedStub}
						</td>
						
						<td style="border: 1px solid black;">
							<input type="text" name="loginField" placeholder="login"/>
						</td>
						
						<td style="border: 1px solid black;">
							<input type="email" name="mailField" placeholder="email"/>
						</td>
						
						<td style="border: 1px solid black;">
							<input type="password" name="passwordField" placeholder="password" />
						</td>
						
						<td style="border: 1px solid black;">
							<select name="accountRoleField">
								<c:forEach items="${roles}" var="role">
									<option value="${role.id}">${role.name}</option>
								</c:forEach>
							</select>
						</td>
						
						<td style="border: 1px solid black;">
							<input type="checkbox" name="accountStatus" value="1"/>
						</td>
						
						<td style="border: 1px solid black;">
							<input type="submit" value="${createButtonText}"/>
						</td>
						
					</form>
				</tr>
				
				<c:forEach items="${usersList}" var="user">
					<tr>
						<form action="controller" method="post">
					
							<input type="hidden" name="command" value="updateUserStatusActionCommand" />
							<input type="hidden" name="userToUpdateId" value="${user.id}" />
							
							<td style="border: 1px solid black;">${user.id}</td>
						
							<td style="border: 1px solid black;">${user.login}</td>
						
							<td style="border: 1px solid black;">${user.mail}</td>
						
							<td style="border: 1px solid black;">${user.password}</td>
						
							<td style="border: 1px solid black;">
								<c:forEach items="${roles}" var="role">
									<c:if test="${role.id == user.roleId}">
										${role.name}
									</c:if>
								</c:forEach>
							</td>
							
							<td style="border: 1px solid black;">
								<c:choose>
									<c:when test="${user.status}">
										<input type="checkbox" name="userStatus" value="1" checked />
									</c:when>
									<c:otherwise>
										<input type="checkbox" name="userStatus" value="1" />
									</c:otherwise>								
								</c:choose>
							</td>
					
							<td style="border: 1px solid black;">						
								<input type="submit" value="${applyUpdateButtonText}" />
							</td>
							
						</form>
					</tr>
				</c:forEach>
							
			</table>
		</div>
	</body>
</html>